abhi2705/storeSeStories

- src/app/api/base.api.ts
- src/app/api/brand.api.ts
- src/app/api/index.ts
- src/app/api/story.api.ts
- src/app/app.module.ts
- src/app/models/brand.model.ts
- src/app/models/story.model.ts
- src/app/services/api.service.spec.ts
- src/app/services/api.service.ts
Added API calls for the brands and stories endpoint.
> Added api calls

- angular.json
- src/app/components/brands-tab/brands-tab.component.scss
- src/app/components/share-tab/share-tab.component.html
- src/app/components/share-tab/share-tab.component.ts
- src/assets/manifest.webmanifest
- src/index.html
- src/styles.scss
Added native share tab using WebShare API
> Native share tab

- README.md
- src/app/components/bottom-menu/bottom-menu.component.scss
- src/app/components/home-page/home-page.component.scss
- src/app/components/stories/stories.component.html
- src/app/components/stories/stories.component.scss
- src/app/components/stories/stories.component.ts
- src/index.html
- src/styles.scss
Changed to % instead of vh/vw for sizing to fix viewport size issues in
chrome android.
> fix: Chrome window size issue

- src/app/components/bottom-menu/bottom-menu.component.ts
The cuurent tab shown in themeu was not in sync with the actual page
currently open. Fixed by detecting the current route in the bottom-menu
component.
> fix: Fixed currebt tab issue.

- .gitignore
- package-lock.json
- package.json
- src/_variables.scss
- src/app/api/auth.api.ts
- src/app/api/base.api.ts
- src/app/api/brand.api.ts
- src/app/api/index.ts
- src/app/api/story.api.ts
- src/app/app.module.ts
- src/app/components/home-page/home-page.component.html
- src/app/components/login/login.component.html
- src/app/components/login/login.component.scss
- src/app/components/login/login.component.spec.ts
- src/app/components/login/login.component.ts
- src/app/models/index.ts
- src/app/models/user.model.ts
- src/app/services/auth.service.ts
- src/app/services/authservice.spec.ts
- src/app/services/bearer-interceptor.service.spec.ts
- src/app/services/bearer-interceptor.service.ts
- src/styles.scss
1. Added login form component.
2. Added Interceptor service to automatically add jwt token to request
headers.
3. Added AuthService to centrally co-ordinate auth flow. Used to fetch new token or
verify any existing token.
> Added user authorization

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/favourites/favourites.component.scss
- src/app/components/stories/keyframes.ts
- src/app/components/stories/stories.component.html
- src/app/components/stories/stories.component.scss
- src/app/components/stories/stories.component.ts
- src/styles.scss
> New story transitions

- src/app/components/favourites/favourites.component.scss
- src/app/components/stories/stories.component.html
- src/app/components/stories/stories.component.ts
- src/styles.scss
Fix for stories component for issue #22
> fix: stories request to api

- src/app/api/brand.api.ts
- src/app/app-routing.module.ts
- src/app/components/brand-page/brand-page.component.html
- src/app/components/brand-page/brand-page.component.scss
- src/app/components/brand-page/brand-page.component.spec.ts
- src/app/components/brand-page/brand-page.component.ts
- src/app/models/brand.model.ts
- src/assets/js/shopify.js
- Route for individual brands brands added
- integration with shopify collections.
> feature: Brand pages added

- src/app/components/brand-nav/brand-nav.component.html
- src/app/components/brand-nav/brand-nav.component.ts
> Changed the link to brand/{{brandId}}

- src/app/components/brand-nav/brand-nav.component.html
- src/app/components/brand-nav/brand-nav.component.ts
> fixed brand api

- .dockerignore
- .github/workflows/dev.yml
- .github/workflows/main.yml
- Dockerfile
- Added node_modules cachiing to all the workflows
> Added dependency caching to workflows

- package.json
- src/app/components/login/login.component.html
- src/app/components/login/login.component.ts
- src/app/services/auth.service.ts
- Enter key now submits the form.
- Added a confirmation prompt before logging out.
Fixes #44
> Auth flow improvements.

- src/app/components/blog-page/blog-page.component.scss
- src/app/components/boomarked-blogs/boomarked-blogs.component.scss
- src/app/components/brand-page/brand-page.component.scss
- src/app/components/favourites/favourites.component.html
- src/app/components/favourites/favourites.component.scss
- src/app/components/my-orders/my-orders.component.html
- src/app/components/my-orders/my-orders.component.scss
- src/app/components/my-orders/my-orders.component.ts
- src/app/components/order-page/order-page.component.html
- src/app/components/order-page/order-page.component.scss
- src/app/components/order-page/order-page.component.ts
- src/assets/js/shopify.js
> Backbutton

- src/app/components/brand-nav/brand-nav.component.html
> Changed placeholder text of search bar

- src/app/components/blog-page/blog-page.component.scss
- src/app/components/boomarked-blogs/boomarked-blogs.component.html
- src/app/components/boomarked-blogs/boomarked-blogs.component.scss
- src/app/components/brand-page/brand-page.component.scss
- src/app/components/favourites/favourites.component.html
- src/app/components/favourites/favourites.component.scss
- src/app/components/my-orders/my-orders.component.html
- src/app/components/my-orders/my-orders.component.scss
> Back responsive

- src/app/components/favourites/favourites.component.scss
- src/app/components/stories/stories.component.scss
- liked cards with 6 in a row for large screens
- card height to width ratio maintained for large screen sizes
> Story cards responsiveness changed

- src/app/components/login/login.component.html
- src/app/components/login/login.component.scss
- src/app/components/share-tab/share-tab.component.ts
- Changed create account and login text.
-  Added underline to mode swithc links.
- Removed message from share.
> fix: Minor fixes in login componenr, and share tab

- src/app/components/brand-nav/brand-nav.component.html
- src/app/components/brand-nav/brand-nav.component.scss
Fixed brand nav scroll, so that itemsdon't get trimmed by bottom menu.
> fix: brand nav

- Dockerfile
- gulpfile.js
- package-lock.json
- package.json
Performance imporved by serving compressed files (gzip).
> feat: Added dist compression

- src/app/app.module.ts
- src/app/services/cache-interceptor.service.spec.ts
- src/app/services/cache-interceptor.service.ts
Added service to cache all GET http requests
to the backend API.
> feat: Caching requests

- src/app/components/stories/stories.component.ts
* Smoothens the card sliders transition and animation of the feed.
> Smooth slider

- src/app/app-routing.module.ts
- src/app/components/bottom-menu/bottom-menu.component.html
- src/app/components/login/login.component.html
- src/app/components/login/login.component.scss
- src/app/components/login/login.component.ts
- src/app/services/auth.service.ts
- src/app/services/bearer-interceptor.service.ts
The app now only asks for logging in when
required.
> feat: Removed login on startup.

- src/app/components/stories/stories.component.ts
Fixed story like issue which caused story to get liked
even when user isn't logged in.
> fix: Story like fix

- src/app/components/blog-nav/blog-nav.component.html
- src/app/components/blog-nav/blog-nav.component.scss
Fixed blog nav height to fill 100% of available space.
> fix: Blog nav height fixed
